### ISSUE TITLE
Facebook REST API is deprecated

### ISSUE THREAD

**Issue by ndachez** [crazy-max/CwsShareCount#4]
Since August 7, 2016 > `REST API is deprecated for versions v2.1 and higher (12)`

To fix this bug : 

For the `case self::SN_FACEBOOK:`
Replace :
`$api_url = "http://api.facebook.com/restserver.php?v=1.0&method=links.getStats&urls=" . urlencode($url) . "&format=json";`
By : 
`$api_url = "http://graph.facebook.com/?id=" . urlencode($url);`

**AND**

Replace :
`if (isset($json[0]['total_count'])) { $result = intval($json[0]['total_count']); }`
By : 
`if (isset($json['share']['share_count'])) { $result = intval($json['share']['share_count']); }`

Have a nice day :)

**Comment by crazy-max** [comment]
Thanks!

**Comment by ndachez** [comment]
Hi,

After use, I noticed that Facebook limited the number of requests... I would try to find a less restrictive alternative.

Have a nice day :)

**Comment by crazy-max** [comment]
Ok thanks!
I you have any update do not forget to leave a message ;)

**Comment by crazy-max** [comment]
I have created a new issue for the limitation : #5
